---
- name: Abrir puertos Firewalld para Master
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - 6443/tcp
    - 2379-2380/tcp
    - 10250/tcp
    - 10259/tcp
    - 10257/tcp
    - 8285/udp
    - 8472/udp

- name: Comprobar si el clúster ya está inicializado
  stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_conf

- name: Inicializar el clúster con kubeadm
  command: kubeadm init --apiserver-advertise-address=192.168.10.20 --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU
  when: not k8s_conf.stat.exists

- name: Crear directorio .kube para el usuario root
  file:
    path: /root/.kube
    state: directory

- name: Copiar admin.conf a .kube/config (root)
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes

- name: Crear directorio .kube para el usuario vagrant
  file:
    path: /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant

- name: Copiar admin.conf a la cuenta vagrant
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant
    group: vagrant

- name: Aplicar red Flannel (CNI)
  command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: not k8s_conf.stat.exists

- name: Obtener comando de unión (join)
  command: kubeadm token create --print-join-command
  register: join_command

- name: Guardar comando de unión
  set_fact:
    k8s_join_command: "{{ join_command.stdout }}"
